title: Dalia Katan | Founder, Strategist, Speaker
description: 'Dalia is passionate about the power of curiosity and human connection to drive meaningful growth for businesses.'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:


plugins:
  - jekyll-redirect-from

plugins:
  - jekyll-sitemap