title: 'Dalia Katan | Founder of Presently'
description: 'What might life look like if designed around community, curiosity, and connection?'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:


plugins:
  - jekyll-redirect-from

plugins:
  - jekyll-sitemap