title: Dalia Katan | Founder, Strategist, Speaker
description: 'Hi 👋 I’m Dalia, founder of Presently 🎁 I'm insanely passionate about community, curiosity, and connection.'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:


plugins:
  - jekyll-redirect-from

plugins:
  - jekyll-sitemap