title: Dalia Katan | Strategist, Designer, Author-Speaker
description: 'Dalia is passionate about the power of curiosity and human connection to drive meaningful growth for businesses.'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:


plugins:
  - jekyll-redirect-from

defaults:
- scope:
    path: ""
  values:
    layout: default-sub