brand:
  name: Dalia Katan
menu-string: 

nav:
  - title: About
    url: 'https://daliakatan.com/about'
  - title: Consulting
    url: 'https://daliakatan.com/strategy'
  - title: Speaking
    url: 'https://daliakatan.com/speaker'
  - title: For You
    url: 'https://daliakatan.com/for-you'
  - title: Contact
    url: 'https://daliakatan.com/#contact'

copyright: Copyright &copy; Dalia Katan 2021

social-buttons:
  - icon: fa fa-twitter
    url: 'http://twitter.com/daliakatan'
  - icon: fa fa-linkedin
    url: 'http://linkedin.com/in/daliakatan'
  - icon: fa fa-medium
    url: 'http://medium.com/@dkatan77'

quicklinks:
  - title:  
    url: '#'
  - title:  
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
