brand:
  name: Dalia Katan
menu-string: Menu

nav:

  - title: About
    url: '#about'
  - title: Services
    url: '#services'
  - title: Portfolio
    url: '#portfolio'
  - title: Team
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Dalia Katan 2018

social-buttons:
  - icon: fa fa-linkedin
    url: 'http://linked.com/u/daliakatan'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
