brand:
  name: Dalia Katan
menu-string: 

nav:
  - title: About
    url: '#about'
  - title: Consulting
    url: '#services'
  - title: Speaking
    url: '#speaking'
  - title: Testimonials
    url: '#testimonials'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Dalia Katan 2019

social-buttons:
  - icon: fa fa-linkedin
    url: 'http://linkedin.com/in/daliakatan'
  - icon: fa fa-instagram
    url: 'http://instagram.com/daliakatan'
  - icon: fa fa-twitter
    url: 'http://twitter.com/dalkatan'

quicklinks:
  - title:  
    url: '#'
  - title:  
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
